version: '3.3'
services:
  go:
    build: ./
    environment:
      DB_URL: postgres://mydbuser:mydbpwd@db/mydbname?sslmode=disable
    volumes:
    - ./:/go/goProject  
    depends_on:
      - db  
  db:
    image: postgres
    volumes:
    - ./postgres:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: mydbname
        POSTGRES_USER: mydbuser
        POSTGRES_PASSWORD: mydbpwd
    ports:
      - "5432"